In [0]:
# from google.colab import files

# uploaded = files.upload()

# for fn in uploaded.keys():
#   print('User uploaded file "{name}" with length {length} bytes'.format(
#       name=fn, length=len(uploaded[fn])))

In [0]:
ls

ner_dataset.csv  sample_data/


In [0]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [0]:
df = pd.read_csv('ner_dataset.csv', encoding = "ISO-8859-1")
df = df[:50000]
df.head(10)

Sentence #           Word  POS    Tag
0  Sentence: 1      Thousands  NNS      O
1          NaN             of   IN      O
2          NaN  demonstrators  NNS      O
3          NaN           have  VBP      O
4          NaN        marched  VBN      O
5          NaN        through   IN      O
6          NaN         London  NNP  B-geo
7          NaN             to   TO      O
8          NaN        protest   VB      O
9          NaN            the   DT      O

In [0]:
df = df.fillna(method='ffill')
df['Sentence #'].nunique(), df.Word.nunique(), df.Tag.nunique()

(2270, 7464, 17)

In [0]:
df.groupby('Tag').size().reset_index(name='counts')


Tag  counts
0   B-art      48
1   B-eve      39
2   B-geo    1490
3   B-gpe     968
4   B-nat      18
5   B-org     959
6   B-per     789
7   B-tim     880
8   I-art      27
9   I-eve      33
10  I-geo     303
11  I-gpe      31
12  I-nat       9
13  I-org     689
14  I-per     931
15  I-tim     239
16      O   42547

In [0]:
X = df.drop('Tag', axis=1)
X.head()

Sentence #           Word  POS
0  Sentence: 1      Thousands  NNS
1  Sentence: 1             of   IN
2  Sentence: 1  demonstrators  NNS
3  Sentence: 1           have  VBP
4  Sentence: 1        marched  VBN

In [0]:
v = DictVectorizer(sparse=False)
X = v.fit_transform(X.to_dict('records'))


In [0]:
# type(X)
# from tempfile import TemporaryFile
# outfile = TemporaryFile()

# # x = np.arange(10)
# np.save(outfile, X)

# outfile.seek(0) # Only needed here to simulate closing & reopening file
# # np.load(outfile)
# # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
ls

ner_dataset.csv  sample_data/


In [0]:
y = df.Tag.values
classes = np.unique(y)
classes = classes.tolist()
classes

['B-art',
 'B-eve',
 'B-geo',
 'B-gpe',
 'B-nat',
 'B-org',
 'B-per',
 'B-tim',
 'I-art',
 'I-eve',
 'I-geo',
 'I-gpe',
 'I-nat',
 'I-org',
 'I-per',
 'I-tim',
 'O']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train.shape, y_train.shape,X_test.shape, y_test.shape

((33500, 9774), (33500,), (16500, 9774), (16500,))

In [0]:
per = Perceptron(verbose=10, n_jobs=-1, max_iter=5)
per.partial_fit(X_train, y_train, classes)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.


-- Epoch 1-- Epoch 1

Norm: 11.22, NNZs: 112, Bias: -2.000000, T: 33500, Avg. loss: 0.002239
Total training time: 0.67 seconds.
-- Epoch 1
Norm: 9.54, NNZs: 79, Bias: -3.000000, T: 33500, Avg. loss: 0.001313
Total training time: 0.68 seconds.
-- Epoch 1


[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.7s


Norm: 40.40, NNZs: 906, Bias: -4.000000, T: 33500, Avg. loss: 0.020418
Total training time: 0.70 seconds.
-- Epoch 1
Norm: 49.91, NNZs: 1425, Bias: -3.000000, T: 33500, Avg. loss: 0.041672
Total training time: 0.72 seconds.
-- Epoch 1


[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    1.4s


Norm: 6.86, NNZs: 41, Bias: -3.000000, T: 33500, Avg. loss: 0.000537
Total training time: 0.69 seconds.
-- Epoch 1
Norm: 42.20, NNZs: 1108, Bias: -5.000000, T: 33500, Avg. loss: 0.036030
Total training time: 0.71 seconds.
-- Epoch 1
Norm: 35.89, NNZs: 889, Bias: -4.000000, T: 33500, Avg. loss: 0.023164
Total training time: 0.70 seconds.
-- Epoch 1
Norm: 34.70, NNZs: 693, Bias: -4.000000, T: 33500, Avg. loss: 0.017851
Total training time: 0.70 seconds.
-- Epoch 1
Norm: 8.06, NNZs: 62, Bias: -3.000000, T: 33500, Avg. loss: 0.001104
Total training time: 0.68 seconds.
-- Epoch 1
Norm: 9.75, NNZs: 80, Bias: -3.000000, T: 33500, Avg. loss: 0.001015
Total training time: 0.69 seconds.
-- Epoch 1


[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    3.5s


Norm: 24.96, NNZs: 454, Bias: -3.000000, T: 33500, Avg. loss: 0.011045
Total training time: 0.69 seconds.
-- Epoch 1
Norm: 8.54, NNZs: 64, Bias: -3.000000, T: 33500, Avg. loss: 0.001463
Total training time: 0.70 seconds.
-- Epoch 1
Norm: 5.92, NNZs: 27, Bias: -3.000000, T: 33500, Avg. loss: 0.000239
Total training time: 0.68 seconds.
-- Epoch 1
Norm: 36.73, NNZs: 844, Bias: -5.000000, T: 33500, Avg. loss: 0.023970
Total training time: 0.71 seconds.
-- Epoch 1


[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:    4.9s


Norm: 43.32, NNZs: 1190, Bias: -5.000000, T: 33500, Avg. loss: 0.027433
Total training time: 0.76 seconds.
-- Epoch 1
Norm: 22.34, NNZs: 363, Bias: -3.000000, T: 33500, Avg. loss: 0.011224
Total training time: 0.73 seconds.
Norm: 52.55, NNZs: 1543, Bias: 3.000000, T: 33500, Avg. loss: 0.048030
Total training time: 0.67 seconds.


[Parallel(n_jobs=-1)]: Done  17 out of  17 | elapsed:    6.3s finished


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
      fit_intercept=True, max_iter=5, n_iter=None, n_iter_no_change=5,
      n_jobs=-1, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=10, warm_start=False)

In [0]:
new_classes = classes.copy()
new_classes.pop()
new_classes

['B-art',
 'B-eve',
 'B-geo',
 'B-gpe',
 'B-nat',
 'B-org',
 'B-per',
 'B-tim',
 'I-art',
 'I-eve',
 'I-geo',
 'I-gpe',
 'I-nat',
 'I-org',
 'I-per',
 'I-tim']

In [0]:
print(classification_report(y_pred=per.predict(X_test), y_true=y_test, labels=new_classes))

              precision    recall  f1-score   support

       B-art       0.04      0.08      0.05        13
       B-eve       1.00      0.06      0.11        17
       B-geo       0.29      0.97      0.45       508
       B-gpe       0.91      0.62      0.74       316
       B-nat       0.00      0.00      0.00         8
       B-org       0.67      0.10      0.17       301
       B-per       0.93      0.32      0.47       248
       B-tim       0.90      0.62      0.73       286
       I-art       0.00      0.00      0.00        10
       I-eve       1.00      0.08      0.15        12
       I-geo       0.63      0.17      0.27       101
       I-gpe       1.00      0.10      0.18        10
       I-nat       0.00      0.00      0.00         2
       I-org       1.00      0.04      0.08       243
       I-per       0.76      0.11      0.19       319
       I-tim       0.34      0.17      0.23        75

   micro avg       0.45      0.43      0.44      2469
   macro avg       0.59   

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
sgd = SGDClassifier()
sgd.partial_fit(X_train, y_train, classes)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=None,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
print(classification_report(y_pred=sgd.predict(X_test), y_true=y_test, labels=new_classes))

              precision    recall  f1-score   support

       B-art       0.00      0.00      0.00        13
       B-eve       0.00      0.00      0.00        17
       B-geo       0.66      0.61      0.64       508
       B-gpe       0.89      0.46      0.61       316
       B-nat       0.00      0.00      0.00         8
       B-org       0.34      0.54      0.42       301
       B-per       0.84      0.34      0.48       248
       B-tim       0.93      0.64      0.76       286
       I-art       0.00      0.00      0.00        10
       I-eve       0.00      0.00      0.00        12
       I-geo       0.67      0.18      0.28       101
       I-gpe       0.00      0.00      0.00        10
       I-nat       0.00      0.00      0.00         2
       I-org       0.86      0.28      0.42       243
       I-per       0.39      0.85      0.53       319
       I-tim       1.00      0.01      0.03        75

   micro avg       0.56      0.50      0.53      2469
   macro avg       0.41   

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
!pip install cPickle

  Could not find a version that satisfies the requirement cPickle (from versions: )
No matching distribution found for cPickle


In [0]:
import pickle
# now you can save it to a file
with open('filename.pkl', 'wb') as f:
    pickle.dump(per, f)

# and later you can load it
with open('filename.pkl', 'rb') as f:
    clf = pickle.load(f)

In [0]:
ls

filename.pkl  ner_dataset.csv  sample_data/


In [0]:
print(classification_report(y_pred=clf.predict(X_test), y_true=y_test, labels=new_classes))

              precision    recall  f1-score   support

       B-art       0.04      0.08      0.05        13
       B-eve       1.00      0.06      0.11        17
       B-geo       0.29      0.97      0.45       508
       B-gpe       0.91      0.62      0.74       316
       B-nat       0.00      0.00      0.00         8
       B-org       0.67      0.10      0.17       301
       B-per       0.93      0.32      0.47       248
       B-tim       0.90      0.62      0.73       286
       I-art       0.00      0.00      0.00        10
       I-eve       1.00      0.08      0.15        12
       I-geo       0.63      0.17      0.27       101
       I-gpe       1.00      0.10      0.18        10
       I-nat       0.00      0.00      0.00         2
       I-org       1.00      0.04      0.08       243
       I-per       0.76      0.11      0.19       319
       I-tim       0.34      0.17      0.23        75

   micro avg       0.45      0.43      0.44      2469
   macro avg       0.59   

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
y_pred=clf.predict(X_test)

In [0]:
for i,j,k in zip(X_test[:10],y_test[:10],y_pred[:10]):
  print(i,'___',j,'__',k)

[0. 0. 0. ... 0. 0. 0.] ___ O __ O
[0. 0. 0. ... 0. 0. 0.] ___ O __ O
[0. 0. 0. ... 0. 0. 0.] ___ O __ O
[0. 0. 0. ... 0. 0. 0.] ___ B-gpe __ B-geo
[0. 0. 0. ... 0. 0. 0.] ___ O __ O
[0. 0. 0. ... 0. 0. 0.] ___ O __ O
[0. 0. 1. ... 0. 0. 0.] ___ O __ O
[0. 0. 0. ... 0. 0. 0.] ___ O __ O
[0. 1. 0. ... 0. 0. 0.] ___ O __ O
[0. 0. 0. ... 0. 0. 0.] ___ O __ O


In [0]:
ls

filename.pkl  ner_dataset.csv  sample_data/


In [0]:
from google.colab import files
files.download('filename.pkl') 